apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: apicurio-registry
    appstudio.openshift.io/component: apicurio-registry-qnbk
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: apicurio-registry-qnbk
  namespace: carnalca-srs-tenant
spec:
  url: https://github.com/Apicurio/apicurio-registry
